fragment AuthUser on User {
  id
  username
  email
}

mutation SigninLocal($data: SigninLocalDto!) {
  signinLocal(data: $data) {
    ...AuthUser
  }
}

mutation SignOut {
  signOut {
    ...AuthUser
  }
}

query Me {
  me {
    ...AuthUser
  }
}

